# 环境配置文件
# 支持多环境配置，便于在不同环境间切换

# 开发环境
dev:
  name: "开发环境"
  base_url: "https://dev-api.example.com"  # 替换为实际开发环境地址
  database:
    host: "dev-db.example.com"
    port: 5432
    name: "dev_database"
  auth:
    token: "dev_token_here"
  features:
    debug_mode: true
    mock_external_apis: true

# 测试环境
test:
  name: "测试环境"
  base_url: "https://test-api.example.com"  # 替换为实际测试环境地址
  database:
    host: "test-db.example.com"
    port: 5432
    name: "test_database"
  auth:
    token: "test_token_here"
  features:
    debug_mode: true
    mock_external_apis: false

# 预发布环境
staging:
  name: "预发布环境"
  base_url: "https://staging-api.example.com"  # 替换为实际预发布环境地址
  database:
    host: "staging-db.example.com"
    port: 5432
    name: "staging_database"
  auth:
    token: "staging_token_here"
  features:
    debug_mode: false
    mock_external_apis: false

# 生产环境
prod:
  name: "生产环境"
  base_url: "https://api.example.com"  # 替换为实际生产环境地址
  database:
    host: "prod-db.example.com"
    port: 5432
    name: "prod_database"
  auth:
    token: "prod_token_here"
  features:
    debug_mode: false
    mock_external_apis: false
    read_only_mode: true  # 生产环境只读模式

# 本地环境
local:
  name: "本地环境"
  base_url: "http://localhost:8080"
  database:
    host: "localhost"
    port: 5432
    name: "local_database"
  auth:
    token: "local_token_here"
  features:
    debug_mode: true
    mock_external_apis: true
